"""initial schema

Revision ID: ddb267266304
Revises:
Create Date: 2026-08-06 10:36:20.412781

"""

import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ddb267266304"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Seeded Role IDs — hardcoded, never uuid4(). Every environment must agree on
# these values, and downgrade() deletes exactly these rows (assertion 9).
# uuid.UUID objects, not strings: migrations run over asyncpg, which rejects a
# str bound to a uuid column and will not compare uuid = text.
ROLE_DEVELOPER_ID = uuid.UUID("a1b2c3d4-0000-4000-8000-000000000001")
ROLE_QA_ENGINEER_ID = uuid.UUID("a1b2c3d4-0000-4000-8000-000000000002")

# Native enum types created implicitly by sa.Enum() inside create_table().
# Alembic emits no DROP TYPE for them — downgrade() must do it by hand.
ENUM_TYPE_NAMES = ("document_category", "ingestion_status", "escalation_reason")


def _role_table() -> sa.Table:
    """Minimal ad-hoc table for bulk_insert.

    Deliberately NOT the ORM model: a migration must describe the schema as it
    was at this revision. Importing app.core.models would make this file change
    meaning whenever the model changes.
    """
    return sa.table(
        "role",
        sa.column("id", sa.UUID()),
        sa.column("name", sa.String()),
        sa.column("description", sa.Text()),
        sa.column("persona_prompt", sa.Text()),
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("persona_prompt", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("keycloak_id", sa.String(length=255), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_owner", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("NOT is_owner OR is_admin", name="ck_owner_implies_admin"),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("keycloak_id"),
    )
    op.create_index(
        "idx_single_owner",
        "user",
        ["is_owner"],
        unique=True,
        postgresql_where=sa.text("is_owner IS true"),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column("answer_text", sa.Text(), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("was_escalated", sa.Boolean(), nullable=False),
        sa.Column("cache_hit", sa.Boolean(), nullable=False),
        sa.Column("chunks_used", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("namespace_queried", sa.String(length=255), nullable=True),
        sa.Column("response_time_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "document",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_path", sa.String(length=1024), nullable=False),
        sa.Column("original_filename", sa.String(length=512), nullable=False),
        sa.Column(
            "category",
            sa.Enum("technical", "quality", "projects", "company", name="document_category"),
            nullable=False,
        ),
        sa.Column("restricted", sa.Boolean(), nullable=False),
        sa.Column("doc_hash", sa.String(length=64), nullable=False),
        sa.Column("uploaded_by", sa.UUID(), nullable=False),
        sa.Column("last_ingested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column(
            "ingestion_status",
            sa.Enum("pending", "running", "done", "failed", name="ingestion_status"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("doc_hash"),
    )
    op.create_table(
        "document_image",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("image_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["document.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("document_id", "image_id"),
    )
    op.create_table(
        "escalation_event",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("audit_log_id", sa.UUID(), nullable=False),
        sa.Column(
            "reason",
            sa.Enum("faithfulness_failure", "relevance_failure", name="escalation_reason"),
            nullable=False,
        ),
        sa.Column(
            "notified_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.UUID(), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["audit_log_id"],
            ["audit_log.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    # Role seed — hand-written, autogenerate never emits data.
    # IDs are hardcoded constants, NOT uuid4(): every environment must agree on
    # them, and downgrade() deletes exactly these rows. created_at is omitted so
    # the server_default applies.
    op.bulk_insert(
        _role_table(),
        [
            {
                "id": ROLE_DEVELOPER_ID,
                "name": "developer",
                "description": "Software developer — builds and maintains the codebase.",
                "persona_prompt": (
                    "You are answering a software developer. Be precise and technical. "
                    "Prefer code, file paths, config keys and exact identifiers over prose."
                ),
            },
            {
                "id": ROLE_QA_ENGINEER_ID,
                "name": "qa_engineer",
                "description": "QA engineer — validates behaviour against requirements.",
                "persona_prompt": (
                    "You are answering a QA engineer. Frame answers around expected "
                    "behaviour, acceptance criteria, test steps and edge cases."
                ),
            },
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("escalation_event")
    op.drop_table("document_image")
    op.drop_table("document")
    op.drop_table("audit_log")
    op.drop_index(
        "idx_single_owner", table_name="user", postgresql_where=sa.text("is_owner IS true")
    )
    op.drop_table("user")

    # Seed removal (assertion 9) — must sit here, after `user` is gone and before
    # `role` is dropped. user.role_id carries an FK to role.id, so deleting these
    # rows while any user row still references them raises ForeignKeyViolationError.
    op.execute(
        sa.text("DELETE FROM role WHERE id IN (:dev_id, :qa_id)").bindparams(
            dev_id=ROLE_DEVELOPER_ID, qa_id=ROLE_QA_ENGINEER_ID
        )
    )

    op.drop_table("role")
    # ### end Alembic commands ###

    # Native enum types outlive their tables. Alembic emits drop_table but never
    # DROP TYPE, so without this the next `upgrade head` fails with
    # `type "document_category" already exists` (assertion 5).
    bind = op.get_bind()
    for type_name in ENUM_TYPE_NAMES:
        sa.Enum(name=type_name).drop(bind, checkfirst=False)
